# Generated by Django 5.0.2 on 2024-02-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_2',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
