# Generated by Django 5.0.2 on 2024-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_site', '0002_remove_product_image_url_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_2', models.ImageField(blank=True, upload_to='blogg')),
            ],
        ),
    ]
